updates fixing CONSUM <string> command which returns multiple mibs

diff --git a/check_snmp_printer b/check_snmp_printer
--- a/check_snmp_printer
+++ b/check_snmp_printer
@@ -167,59 +167,70 @@ exit $EXITCODE
 
 ###einzelne abfrage
 else
-ID=`$SNMPWALK -v1 -c $COMMUNITY $HOSTIP  1.3.6.1.2.1.43.11.1.1.6.1 2>/dev/null |$EGREP -i -e "$1"|cut -d "=" -f1|cut -d "." -f8`
+PID=`$SNMPWALK -v1 -c $COMMUNITY $HOSTIP  1.3.6.1.2.1.43.11.1.1.6.1 2>/dev/null |$EGREP -i -e "$1"|cut -d "=" -f1|cut -d "." -f8`
 fi
 fi
+for ID in $PID
+do
 NAME=`$SNMPGET -v1 -c $COMMUNITY $HOSTIP  1.3.6.1.2.1.43.11.1.1.6.1.$ID 2>/dev/null |cut -d " " -f4- |tr -d "\""`
 if [ -z "$NAME" ]
-	then 
-	echo "Error OID not found,maybe your Printer does not support checking this device, call me with Option CONSUM TEST or see help"
-	exit 3 
+        then
+        echo "Error OID not found,maybe your Printer does not support checking this device, call me with Option CONSUM TEST or see help"
+        exit 3
 fi
 
 STATUS=`$SNMPGET -v1 -c $COMMUNITY $HOSTIP  1.3.6.1.2.1.43.11.1.1.9.1.$ID 2>/dev/null |cut -d " " -f4- |tr -d "\""`
 FULL=`$SNMPGET -v1 -c $COMMUNITY $HOSTIP  1.3.6.1.2.1.43.11.1.1.8.1.$ID 2>/dev/null |cut -d " " -f4- |tr -d "\""`
-if [ "$FULL" -gt 0 ] && [ "$STATUS" -gt 0 ]
+
+
+####debug
+#echo found $ID with name $NAME , full state: $FULL , actual state: $STATUS
+
+if [ "$FULL" -gt 0 ] && [ "$STATUS" -ge 0 ]
 then
 	let "STATUS= $STATUS * 100 / $FULL"
-	if [ "$STATUS" -ge "10" ]
-		then
-		echo "OK,$NAME is at $STATUS%|$NAME=$STATUS;;$FULL;"
-        	exit 0
-		else 
-		if [ "$STATUS" -lt "10" ] && [ "$STATUS" -ge "5" ]
-			then
- 			echo "WARNING,$NAME is at $STATUS%|$NAME=$STATUS;;$FULL;"
-        		exit 1 
-			else 
-			if [ "$STATUS" -lt "5" ]
-				then
-				echo "CRITICAL,$NAME is at $STATUS%|$NAME=$STATUS;;$FULL;"
-        			exit 2
-			fi
-		fi
-	fi
-
-else
-if [ "$STATUS" = "-3" ]
-	then
-	echo "$NAME is OK"
-	exit 0
+        if [ "$STATUS" -ge "10" ]
+        then
+		EXITSTRING="$EXITSTRING OK,$NAME is at $STATUS%"
+                PERFDAT="$PERFDAT $NAME=$STATUS;;$FULL;"
 	else
-	if [ "$STATUS" = "-2" ]
-		then 
-		echo "$NAME is at warning level"
-		exit 1
+		if [ "$STATUS" -lt "10" ] && [ "$STATUS" -ge "5" ]
+		then
+			EXITSTRING="$EXITSTRING, WARNING,$NAME is at $STATUS%"
+			PERFDAT="$PERFDAT $NAME=$STATUS;;$FULL;"
+			EXITCODE=1
 		else
-		if [ "$STATUS" = "0" ]
-                	then 
-			echo "$NAME is at critical level"
-			exit 2
-		fi
+			if [ "$STATUS" -lt "5" ]
+                        then
+				EXITSTRING="$EXITSTRING CRITICAL,$NAME is at $STATUS%"
+				PERFDAT="$PERFDAT $NAME=$STATUS;;$FULL;"
+        	                EXITCODE=2
+                        fi
+                fi
+        fi
+	#echo "current exit code: $EXITCODE"
+else
+	if [ "$STATUS" = "-3" ]
+	then
+		EXITSTRING="$EXITSTRING OK,$NAME is FULL"
+        else
+        	if [ "$STATUS" = "-2" ]
+                then
+			EXITSTRING="$EXITSTRING WARNING,$NAME is at $STATUS%"
+                        EXITCODE=1
+		else
+                	if [ "$STATUS" = "0" ]
+			then
+				EXITSTRING="$EXITSTRING CRITICAL,$NAME is at $STATUS%"
+				EXITCODE=2
+                	fi
+        	fi
 	fi
 fi
 
-fi
+done
+echo "$EXITSTRING|$PERFDAT"
+exit $EXITCODE
 }
 
 
